<style>
    #vehicles-table th {
        text-transform: capitalize;
    }
</style>
<h1>Vehicles List</h1>
<div class="card">
    <div class="card-body">
        <div class="form-group">
            <label for="vehicle-type">Vehicle Type</label>
            <select class="form-control" id="vehicle-type">
                <option value="">Select Vehicle Type</option>
                <option value="sedan">Sedan</option>
                <option value="motorcycle">Motorcycle</option>
            </select>
        </div>
        <table class="table" id="vehicles-table"></table>
    </div>
</div>